### ISSUE TITLE
Easy customization for displaying column of strings

### ISSUE THREAD

**Issue by AruniRC** [mtli/HTML4Vision#1]
Thank you for a really handy library for quick visualizations. 

A suggestion: 

However, it does not seem very straightforward to display a list of strings along with the columns for ID and images. This use case would come up when we want to show the image filename along with the images themselves in the generated HTML columns.

**Comment by mtli** [comment]
Thanks for your suggestions!

But I am not sure what you need. It's actually quite handy to display filenames:
```python
from glob import glob
from html4vision import Col, imagetable

paths = 'output/*.jpg'

# table description
cols = [
    Col('id1', 'ID'),
    Col('img', 'Image', paths),
    Col('img', 'File Path', sorted(glob(paths))),
]

# html table generation
imagetable(cols)
```
