### ISSUE TITLE
support displaying table as "text"?

### ISSUE THREAD

**Issue by yzou2** [mtli/HTML4Vision#16]
Currently I am trying to show a table for a single row in the "text" column. E.g
![Screenshot 2023-02-13 at 11 31 26 PM](https://user-images.githubusercontent.com/20036855/218668945-04a75dd9-a26c-4165-88df-089c6663ff42.png)

I have tried to use table strings with '\n'. But looks like the html generation ignore the new line operator. I have also added `<br>` or `<br />` in the strings, but also failed. Any way to display a table in the generated html?

**Comment by mtli** [comment]
Hi, you can probably add `escape=false` to [here](https://github.com/mtli/HTML4Vision/blob/master/html4vision/common.py#L67-L70) for your purpose.

**Comment by yzou2** [comment]
Hi thanks for the prompt response. I have tried the following in https://github.com/mtli/HTML4Vision/blob/master/html4vision/common.py#L68

`return td(**kwargs).add(a(*args, href=hrefs[idx], target='_blank', escape=false))
`

But it still does not work (no error was raised, it's just still string displayed rather than table). Do I set it incorrectly?

**Comment by mtli** [comment]
Try adding it to td() instead of a(). Also, this code path is used only when you use hyperlinks. If you are not using links, you should probably modify the statement after else, or modify both paths way for consistency.

**Comment by yzou2** [comment]
Thanks for the advice! I have tried the following code as you suggested. But it still does not print the table-type strings given the '\n' operator. Do you have other ideas in mind for a fix?

```
if hrefs and idx < len(hrefs) and hrefs[idx]:
    return td(**kwargs,escape=False).add(a(*args, href=hrefs[idx], target='_blank'))
else:
    return td(*args, **kwargs, escape=False)
```

**Comment by mtli** [comment]
'\n' is for python, try \<br\> for HTML.

**Comment by yzou2** [comment]
I have tried both `<br>` and `<br />`, still does not work. Actually the `<br>` is printed out in the strings  
![Screenshot 2023-02-15 at 5 00 33 PM](https://user-images.githubusercontent.com/20036855/219230872-08383052-40cf-491b-a5c5-76d90fc48692.png)

**Comment by yzou2** [comment]
Is there a way to convert the `<br>` into something that can be understood by html to break lines?

**Comment by mtli** [comment]
Hmm, I haven't used the dominate library for a while. Maybe you can try wrapping it around with the text tag: `td(text(*args, **kwargs, escape=False))`?

**Comment by yzou2** [comment]
Thanks for the advice! I make it works by 

```
if isinstance(args[0],str):
    return td(text(*args, **kwargs, escape=False))
return td(*args, **kwargs, escape=False)
```

**Comment by mtli** [comment]
Glad that you got it working!
