### ISSUE TITLE
cannot display images not in current folder

### ISSUE THREAD

**Issue by arjung128** [mtli/HTML4Vision#3]
I have the following code:

```
cols = [
    Col('id1', 'ID'),
    Col('img', 'Img_1', './0.jpg'),
    Col('img', 'Img_2', './../0.jpg'),
]

# html table generation
imagetable(cols)
```

Img_1 displays perfectly fine but I get a little blue question mark in place of Img_2. I have tried a variety of images and a variety of image paths and it seems like the image needs to be in the current folder to be displayed correctly (instead of a little blue question mark). Any ideas how this can be resolved? Thanks!

**Comment by mtli** [comment]
This depends on whether you are serving the webpage through an HTTP server. By default, a server does not allow parent directory access. If you just click and open the webpage like a regular file, it should work.

**Comment by arjung128** [comment]
The code was on a Jupyter Notebook. When I click on the generated index.html (in the jupyter notebook interface), I observe the behavior mentioned above. Is this what you are suggesting?

**Comment by arjung128** [comment]
Is there a way to allow parent directory access? Absolute paths don't seem to work either...

**Comment by mtli** [comment]
Yes, jupyter notebook is an HTTP server and this is a security measure. You need to serve webpages from the parent directory. It doesn't have to be juypter notebook, and I recommend you use the one-line server provided by this package (see serving webpage section in the readme).

**Comment by arjung128** [comment]
Thank you for your prompt replies and for bearing with me. But sorry, I still seem to be struggling to get this to work as expected.

The dataset is stored under `//scratch/someone_else/dataset/` and my jupyter notebook and index.html file is in `//scratch/me/` and when I launch a server from `//scratch` using `python -m html4vision.server` I still get little blue question marks (this is when using absolute paths for images in `//scratch/someone_else/dataset/`)... But when I try to display images in `//scratch/me`, it works (only when using relative path, not when using absolute path). Any ideas what I am doing wrong?

Thanks for your great work and for being so responsive.

**Comment by arjung128** [comment]
@mtli Hi, I'm sorry to bug you but I'm still struggling to display images not in my current directory (please see my last post for a more detailed description). And I cannot afford to move the dataset into my directory, nor do I have write permissions to the dataset to move my script there. Do you have any ideas about how I can resolve this? Thanks!

**Comment by mtli** [comment]
Hi, I think your question is about how to use an HTTP server, not a question about this repository. I recommend you check out related materials on path issues regarding HTTP servers. When you serve webpages, you have to use a relative path and that path needs to be relative to your server's serving path. Another tip for debugging, you can create a minimal example on your local machine first without using any HTTP servers.

**Comment by mtli** [comment]
To make it clearer, when you serve webpages, the anchor for the relative path is not the current file, but the server's serving path. In your example, that means when you serve from `scratch`, you should write `someone_else/dataset/img_0.jpg'.

**Comment by arjung128** [comment]
Got it. Thanks for your help!
