### ISSUE TITLE
Sorting order might be off

### ISSUE THREAD

**Issue by kampelmuehler** [mtli/HTML4Vision#9]
https://github.com/mtli/HTML4Vision/blob/8daa9f1c6558b3039da01cab9ca82750c71c714a/html4vision/common.py#L39

`sorted()` will return the wrong order since it's numerical sort and not natural sort. So `list(range(101))` will be something like `[0, 1, 10, 100, 11]` etc.. This could easily be resolved by using  `natsorted` from the the `natsort` package. Didn't submit a PR since I see this as a topic for discussion.

**Comment by mtli** [comment]
Hi, thanks for this useful feedback and for raising this issue as a discussion! While it's true that `sorted()` may return the undesired results, it might be preferable to keep it consistent with standard system utilities (e.g., `ls` or Windows File Explorer) to avoid unexpected outcomes. As a workaround, the filenames can be zero-padded (e.g., 000103.jpg).
